### ISSUE TITLE
not working, all values are zero

### ISSUE THREAD

**Issue by c-m0s** [mgarrix/MMM-ShellyEMMeter#2]
Found your module yesterday and love it -

Unfortunately I don't get any readings from the Shelly device.

When I do execute the URL in a browser on th device I do run my MagicMirror Instance on I do get the status report of the Shelly Device.

Is it possible, that the syntax go the devices status message changed in the meantime, @mgarrix ?

**Comment by mgarrix** [comment]
When you call the url http://ShellyEM-ip/status you should receive as a reply the JSON of the Shelly module, something like this: "_{"wifi_sta":{"wifi_sta":{"connected":true, "ssid": "yourSSID", "ip": "ShellyIP-address", "rssi":-91}, "cloud":{"enabled":true, "connected":true}, "mqtt".... etc_. If so, you're all set. 
I don't think anything has changed in the meantime.

**Comment by c-m0s** [comment]
Oh you are really enforcing the static IP, I see.
It read more like a suggestion and the IPs in my network are quasi-static, so I did not follow this recommendation 🫣
Thanks. I'll try it..

**Comment by mgarrix** [comment]
You should be able to specify some devices with a static ip directly from the router console.
