### ISSUE TITLE
No repository field.

### ISSUE THREAD

**Issue by pasakiller** [mgarrix/MMM-ShellyEMMeter#3]
I get this while installatoin:

`pi@raspberrypi:~/MagicMirror/modules/MMM-ShellyEMMeter $ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN mmm-shellyemmeter@1.0.0 No repository field.

added 71 packages from 78 contributors and audited 71 packages in 14.071s

3 packages are looking for funding
  run `npm fund` for details

found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
`

How can I fix this? 
Best regards

**Comment by mgarrix** [comment]
Hi,
they just seem to be warnings.
May I know which version of Node and NPM are you using?

**Comment by pasakiller** [comment]
Hi,
I have 
pi@raspberrypi:~ $ node -v
v10.24.1

pi@raspberrypi:~ $ npm -v
6.14.12

**Comment by pasakiller** [comment]
okay now I have the latest version, but I get still only zeros fpr the consumption values. 

pi@raspberrypi:~ $ node -v
v18.18.2
pi@raspberrypi:~ $ npm -v
10.2.0

**Comment by mgarrix** [comment]
Hi, checks the prerequisites as described:
The default 'clock' module must be active because the 'ShellyEMMeter' module uses events triggered by 'clock' to call Shelly on the lan. In addition, **sendNotifications: true** must be set in the configuration of the 'clock' module.

**Comment by pasakiller** [comment]
mgarrix I have added the sendNotifications: true in the config file. Now it is working :-)
Thank you very much. 
lovely regards fromSwitzerland
